const express = require('express');
const router = express.Router();
const storeController = require('../controllers/store.controller');
const authMiddleware = require('../middleware/auth.middleware');
const roleMiddleware = require('../middleware/role.middleware');
router.use(authMiddleware);
router.use(roleMiddleware(['STORE_OWNER']));
router.get('/dashboard', storeController.getDashboard);
router.get('/ratings', storeController.getRatings);
module.exports = router;
